config/routes.rb
Estacionamento::Application.routes.draw do

  resources :notifications

  root :to => "notifications#index"
end

app/models/atributo.rb
class Atributo < ActiveRecord::Base
  self.table_name = :tb_atributo
  set_primary_key 'id_atributo'

  has_many :chamados, :through => :chamado_atributo, :foreign_key => "id_atributo_fk"

  scope :placa, where(:id_atributo => [219, 231, 267])
end

app/models/bairro.rb
class Bairro < ActiveRecord::Base
  self.table_name = :tb_bairro
  set_primary_key 'id_bairro'

  has_many :bairro_logradouros, :foreign_key => "id_bairro_fk"
  has_many :chamados, :through => :bairro_logradouros, :foreign_key => "id_bairro_fk"
end

app/models/bairro_logradouro.rb
class BairroLogradouro < ActiveRecord::Base
  self.table_name = :tb_bairro_logradouro
  set_primary_key 'id_bairro_logradouro'

  has_many :chamado, :foreign_key => "id_bairro_logradouro_fk"
  belongs_to :bairro, :foreign_key => "id_bairro_fk"
  belongs_to :logradouro, :foreign_key => "id_logradouro_fk"

  default_scope includes(:bairro, :logradouro)
end

app/models/chamado.rb
class Chamado < ActiveRecord::Base
  self.table_name = :tb_chamado
  set_primary_key 'id_chamado'

  has_many :atributos, :through => :chamado_atributos, :foreign_key => "id_chamado_fk"
  has_many :chamado_atributos, :foreign_key => "id_chamado_fk"
  has_one :subtipo, :through => :classificacao_chamado, :foreign_key => "id_chamado_fk"
  has_one :classificacao_chamado, :foreign_key => "id_chamado_fk"
  belongs_to :status, :foreign_key => "id_status_fk"
  belongs_to :bairro_logradouro, :foreign_key => "id_bairro_logradouro_fk"
end

app/models/chamado_atributo.rb
class ChamadoAtributo < ActiveRecord::Base
  self.table_name = :tb_chamado_atributo
  set_primary_key 'id_chamado_atributo'

  belongs_to :chamado, :foreign_key => "id_chamado_fk"
  belongs_to :atributo, :foreign_key => "id_atributo_fk"

  scope :placa, where(:id_atributo_fk => [219, 231, 267])
end

app/models/classificacao_chamado.rb
class ClassificacaoChamado < ActiveRecord::Base
  self.table_name = :tb_classificacao_chamado
  set_primary_key 'id_classificacao_chamado'

  belongs_to :chamado, :foreign_key => "id_chamado_fk"
  belongs_to :subtipo, :foreign_key => "id_subtipo_fk"
end

app/models/logradouro.rb
class Logradouro < ActiveRecord::Base
  self.table_name = :tb_logradouro
  set_primary_key 'id_logradouro'

  has_many :bairro_logradouros, :foreign_key => "id_logradouro_fk"
  has_many :chamados, :through => :bairro_logradouros, :foreign_key => "id_logradouro_fk"
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :bairro, :cep, :chamado_id, :complemento, :logradouro, :numero, :placa, :reported_at, :subtipo

  belongs_to :chamado
end

app/models/status.rb
class Status < ActiveRecord::Base
  self.table_name = :tb_status
  set_primary_key 'id_status'

  has_many :chamados, :foreign_key => "id_status_fk"
end

app/models/subtipo.rb
class Subtipo < ActiveRecord::Base
  self.table_name = :tb_subtipo
  set_primary_key 'id_subtipo'

  has_many :chamados, :through => :classificacao_chamado, :foreign_key => "id_status_fk"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @q = Notification.order("reported_at DESC").search(params[:q])
    @notifications = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def show
    @notification = Notification.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Estacionamento" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div id="wrap">
      <div class="navbar navbar-fluid-top" style="border-radius: 0;">
        <div class="navbar-inner">
          <div class="container-fluid">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">
              <%= image_tag "logo-advertencia-cidada-150.png", :alt => "Advertência Cidadã", :style => "height: 100px; float: left" %>
              <h2 id="brand-name" style="margin-left: 20px; font-size: 30px; font-family: verdana; font-weight: bold; line-height: 28px; float: left; margin-top: 24px">
                ADVERTÊNCIA CIDADÃ<br /><small style="font-size: 22px">Cidadão concientizando cidadão</small>
              </h2>
            </a>
            <div class="container-fluid nav-collapse">
              <ul class="nav">
              </ul>
              <div class="pull-right">
                <%= yield :navbar %>
              </div>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        <div style="height: 10px; background: #2f4d7c"></div>
      </div>

      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      </div> <!-- /container -->
    </div>

    <div id="footer">
      <div class="container">
        <p class="muted credit">Todos os direitos reservados © 2013 <a href="http://cidadera.com">Cidadera</a>.</p>
      </div>
    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/notifications/_form.html.erb
<%= form_for @notification, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :chamado_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :chamado_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :placa, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :placa, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :logradouro, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :logradouro, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :bairro, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :bairro, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :numero, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :numero, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :cep, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cep, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :complemento, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :complemento, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :subtipo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :subtipo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :reported_at, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :reported_at, :class => 'datetime_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                notifications_path, :class => 'btn' %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<%- model_class = Notification -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notifications/index.html.erb
<%- model_class = Notification -%>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:chamado_id) %></th>
      <th><%= model_class.human_attribute_name(:placa) %></th>
      <th><%= model_class.human_attribute_name(:bairro) %></th>
      <th><%= model_class.human_attribute_name(:logradouro) %></th>
      <th>Número</th>
      <th>Infração</th>
      <th>Reportado em</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= link_to notification.id, notification_path(notification) %></td>
        <td><%= notification.chamado_id %></td>
        <td><%= notification.placa %></td>
        <td><%= notification.bairro %></td>
        <td><%= notification.logradouro %></td>
        <td><%= notification.numero %></td>
        <td><%= notification.subtipo.sub("Fiscalização de ", "").capitalize %></td>
        <td><%=l notification.reported_at, :format => :short %></td>
        <td>
          <%= link_to "Visualizar",
                      notification_path(notification),
                      :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      notification_path(notification),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
  <div style="float: left">
    <%= page_entries_info @notifications, :entry_name => "advertência" %>
  </div>
  <div style="float: right">
    <%= paginate @notifications %>
  </div>
</div>

<% content_for :navbar do %>
  <%= search_form_for @q do |f| %>
    <div class="controls controls-row">
      <%= f.text_field :chamado_id_eq, :placeholder => "Chamado", :class => "input-medium" %>
      <%= f.text_field :placa_eq, :placeholder => "Placa", :class => "input-medium" %>
      <%= f.text_field :bairro_cont, :placeholder => "Bairro", :class => "input-medium" %>
    </div>
    <div class="controls controls-row">
      <%= f.text_field :reported_at_gteq, :placeholder => "De", :class => "input-medium" %>
      <%= f.text_field :reported_at_lteq, :placeholder => "Até", :class => "input-medium" %>
      <%= f.submit "Buscar", :class => "btn" %>
    </div>
  <% end %>
<% end %>

app/views/notifications/new.html.erb
<%- model_class = Notification -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notifications/show.html.erb
<%- model_class = Notification -%>

<div class="row-fluid">
  <div class="span6">
    <div class="advertencia-container" style="background: #2f4d7c; height: 780px; border: 1px solid #AAA; box-shadow: 0px 0px 6px 2px #AAA; margin-bottom: 20px;">
      <div class="advertencia-top" style="background-color: #fff; height: 700px;">
        <div style="background: #2f4d7c; height: 3%; margin-bottom: 6%">
        </div>
        <div style="text-align: center">
          <%= image_tag "logo-advertencia-cidada-150.png", :style => "width: 30%" %>
        </div>
        <div style="margin: 5%; font-size: 24px; line-height: 30px; margin-bottom: 0;">
          <p>Cidadão,</p>
          <p>O veículo de placa <%= @notification.placa %> foi objeto de ocorrência na <strong>Central de Atendimento 1746.</strong></p>
        </div>
        <div style="margin: 5%; font-size: 18px; display: inline-block;  margin-bottom: 0">
          <div style="float: left; width: 50%">
            <p style="margin-bottom: 6px;">Motivo: <%= @notification.subtipo.sub("Fiscalização de ", "").capitalize %></p>
            <p style="margin-bottom: 6px;">Local: <%= @notification.logradouro %>, <%= @notification.numero %></p>
            <p>Data: <%= l @notification.reported_at, :format => :long %></p>
          </div>
          <div style="float: left; width: 50%;">
            <%= image_tag "placa.JPG", :style => "width: 45%; margin-left: 5%" %>
            <%= image_tag "estacionar_na_faixa_amarela.JPG", :style => "width: 45%" %>
          </div>
        </div>
        <div style="margin: 5%; font-size: 18px">
          <p style="color: #F00;">Esta modalidade de infração, quando autuada por autoridade competente, acarreta multa de R$ XXXX e X pontos na carteira.</p>
          <p>Respeitar o próximo é um ato de cidadania e todos ganham com sua compreensão e colaboração.</p>
        </div>
      </div>
      <%= image_tag "prefeiturarj.png", :style => "float: right; margin: 8px;" %>
    </div>
  </div>
  <div class="span6">
    <h3>Dados da advertência</h3>
    <br />
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:chamado_id) %>:</strong></dt>
      <dd><%= @notification.chamado_id %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:placa) %>:</strong></dt>
      <dd><%= @notification.placa %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:logradouro) %>:</strong></dt>
      <dd><%= @notification.logradouro %></dd>
      <dt><strong><%= model_class.human_attribute_name(:bairro) %>:</strong></dt>
      <dd><%= @notification.bairro %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:numero) %>:</strong></dt>
      <dd><%= @notification.numero %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:cep) %>:</strong></dt>
      <dd><%= @notification.cep %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:complemento) %>:</strong></dt>
      <dd><%= @notification.complemento %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:subtipo) %>:</strong></dt>
      <dd><%= @notification.subtipo %>&nbsp;</dd>
      <dt><strong><%= model_class.human_attribute_name(:reported_at) %>:</strong></dt>
      <dd><%= @notification.reported_at %>&nbsp;</dd>
    </dl>
  </div>
</div>

<% content_for :navbar do %>
  <div style="margin-top: 40px">
    <%= link_to "Imprimir PDF", "#", :class => 'btn'  %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                notification_path(@notification),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                notifications_path, :class => 'btn'  %>
  </div>
<% end %>

<style type="text/css">
#wrap {
  background: #f8f8f8;
}
</style>